.TH HELLO 1 "March 9 2019" hello "User Commands"
.SH NAME
.B hello
\- demo program
.SH SYNOPSIS
.B hello
.SH DESCRIPTION
.\" Ragged right
.ad 1
.\" Disable hyphenation
.nh
The
.B hello
program is a simple demo which prints a random
double including its fractional part, the same
number rounded, and finally a message \(lq\f(CWHello, World!\fP\(rq\&
followed by a newline.
.SH EXAMPLE
.PP
An example may make understanding this command easier.
.sp 1
.ne 2
.RS
.nf
.nh
\f(CW$hello
536671876.141593 becomes 536671876.000000: Hello, World!\fP
.hy 1
.fi
.RE
.sp 1
.SH AUTHOR
The
.B hello
command was written by
.IR "Ima Koder" .
